name: data_update

on:
  schedule:
     - cron: '0 0 * * *'
  workflow_dispatch:
   
jobs:
  update-data:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.x
          
      - name: Install dependencies
        run: |
          pip install pandas yfinance

      - name: Check out code
        uses: actions/checkout@v3

      - name: Run Python script
        run: python yh.py
        
      - name: Upload CSV as Artifact
        uses: actions/upload-artifact@v2
        with:
          name: output-csv  # The name of the artifact
          path: sp.csv      # The path to the file you want to upload
